### ISSUE TITLE
question

### ISSUE THREAD

**Issue by BotterManTingGoes** [mic0ishere/copy-raw-message#3]
Is copy embed supposed to be a button in the bottom right of the embed that says copy? because I thought the new update copied the actual format whole embed and not just the text which you can select with your mouse and copy.

**Comment by mic0ishere** [comment]
Hey, copy embed button is supposed to copy array/single embed object from message.

Copy Embed button copies array `[ {}, {} ]` or one `{}` of embed objects:
```
{
  type: "rich",
  color: "#fff",
  ...
}
```

Copy Message Content on the other end, copies plain text (content property on message object) and/or attachments url(s).

---
Let me know if you have any more questions, or this issue will be closed in 24 hours.
